import type { Metadata } from "next";
import { Afacad, Inter } from "next/font/google";
import "./globals.css";
import Theming from "@/hoc/theme-provider.";

// const inter = Afacad({
//   subsets: ["latin"],
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theming>{children}</Theming>
      </body>
    </html>
  );
}
